apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-k8s-hpa
  namespace: hello-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-k8s-deployment
  # The deployment name should match the one defined in hello-k8s-deployment.yaml
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
