apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  namespace: hello-ns # Namespace where the service is created
spec:
  type: NodePort # Service Type
  selector:
    app/component: backend-api
  ports:
  - port: 5000 # Service Port
    targetPort: 5000 # Container Port
    nodePort: 30000 # Node Port (optional)
