apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-deployment
  namespace: hello-ns # Namespace where the deployment is created
spec:
  replicas: 3
  selector:
    matchLabels:
      app/component: backend-api
  template:
    metadata:
      name: hello-k8s
      labels:
        app/name: hello-k8s
        app/component: backend-api
    spec:
      containers:
      - name: hello-k8s-container
        image: m0dd/hello-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 5000
        livelinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 8
